### ISSUE TITLE
Container styles are broken

### ISSUE THREAD

**Issue by anseki** [andreruffert/rangeslider.js#112]
Hi, thanks for your plugin.

I put the range element into the `div` element. The styles (`overflow` etc.) of this element are controlled by the other code.
Then, those styles are broken when rangeslider is initialized.
The `display` property seems to be saved before getting size, and it is restored later.
https://github.com/andreruffert/rangeslider.js/blob/develop/src/rangeslider.js#L126
But, other properties are not. These properties which were set by the other code are cleared all.

**Comment by andreruffert** [comment]
@anseki a CodePen etc. would be helpful!

**Comment by anseki** [comment]
Ok. Just 2 cases are here.
http://jsfiddle.net/wjLcx04n/

Case 1:
Click "init 1" button.

Case 2:
Click "collapse" button, and click "init 2" button.

CSS properties `height`, `overflow`, and `visibility` are broken.
Those inline-styles are overwritten to ''.
