### ISSUE TITLE
Change event firing continuously

### ISSUE THREAD

**Issue by thelucid** [andreruffert/rangeslider.js#115]
The change event fires continually rather than at the end of the slide like standard browser implementations. Perhaps there should be a 'changing' event added and 'change' made to perform correctly.

**Comment by andreruffert** [comment]
Hey @thelucid thanks for pointing this out!
Can u please double-check pr #118 which should fix this issue!?

**Comment by thelucid** [comment]
@andreruffert That looks perfect, will give it a go. The only trouble is that there is now not a way to get the continial behaviour from before for things like updating an output element... or do you just subscribe to the move event in that case?

**Comment by andreruffert** [comment]
@thelucid k. I have a different solution which works like the native implementation.
> See PR #121

If the handle is moving it changes the value and fires the [`input`](https://developer.mozilla.org/en-US/docs/Web/Events/input) event.
If the handle is released it just fires the [`change`](https://developer.mozilla.org/en-US/docs/Web/Events/change) event.

That's it basicly :ghost:

**Comment by thelucid** [comment]
@andreruffert Sorry for the slow response... just tested it, it works great and allows me to remove a lot of hacks from my code. Thanks. :ok_hand:

**Comment by andreruffert** [comment]
![](http://media.giphy.com/media/Hux5J5NqWRA40/giphy.gif)
