### ISSUE TITLE
TypeError element is null

### ISSUE THREAD

**Issue by tompradana** [andreruffert/rangeslider.js#122]
This is an error in Firebug I keep seeing.
TypeError: element is null

I get the elements via ajax
// ajax request
var shortcode = $(this).data('shortcode');
$.ajax({
            type: 'POST',
            url: ajaxurl,
            dataType: 'html',
            data: {
                action: 'get_element_settings',
                shortcode: shortcode
            },
            beforeSend: function() {
            },
            success: function(data) {
               // get slider element  
                $tmd_shortcode_module_settings.html(data);

               // range slider handle
                $('.tmd-shortcode-setting-type-range-slider').each(function() {
                    var $this = $(this),
                        $slider = $this.find('.tmd-shortcodes-range-slider'),
                        $output = $this.find('.output');
                    $slider.rangeslider({
                        polyfill: false,
                        rangeClass: 'tmd-rangeslider',
                        fillClass: 'tmd-rangeslider-fill',
                        handleClass: 'tmd-rangeslider-handle',
                        onSlide: function(position, value) {
                            $output.val(value);
                        }
                    });
                    $output.on('keyup blur', function(e) {
                        var val = $(this).val();
                        $slider.val(val).change();
                    });
                });
            }
});

for first request, nothing error

**Comment by andreruffert** [comment]
It's hard for me to comprehend this.
I guess the problem is `element` in the console error is defined with `$slider = $this.find('.tmd-shortcodes-range-slider'),` an the `$slider` selector didn't match any elements...
