### ISSUE TITLE
slider 'step' query

### ISSUE THREAD

**Issue by cjhill2015** [andreruffert/rangeslider.js#130]
Hi,

I love this slider, it works so well, brilliant work!

I have one question.

At the moments i have the slider set up so my numbers increase in increments of 6 like so...

6,12,18,24,30,36,42,48,54,60

however i want the slider to increase by increments of 12 when it reaches 36 thus skipping out '42' and '54' so that when i move the slider it can be pulled along to the following...

6,12,18,24,30,36,48,60

is there a way that i can do this in js or html?

Thanks.

Chris

**Comment by andreruffert** [comment]
Duplicate to #133.
