### ISSUE TITLE
Add function to re-initialize slider

### ISSUE THREAD

**Issue by opatut** [andreruffert/rangeslider.js#137]
Currently, the min/max/step values are retrieved from the DOM attributes in the constructor. Please add a function like `.rangeslider('reinitialize')` to fetch them anew without having to destroy the instance and reconfigure it (aka keep callbacks etc from orginal initialization unless overwritten).

**Comment by andreruffert** [comment]
@opatut thanks for your feedback. Check #139.

**Comment by opatut** [comment]
Awesome! Thank you very much.
