### ISSUE TITLE
Link to url

### ISSUE THREAD

**Issue by rossweston** [andreruffert/rangeslider.js#143]
Hi Andre,

Hope all is well.

I was wondering if you could help me edit your range slider. http://andreruffert.github.io/rangeslider.js/

What I would like it to do is go to specific url depending on where in slider you select.

For example if the range was 1-5 and you moved the slider to 3 you would go to a specific url…

Is that possible with your slider?

And if so, how could I embed that into a wordpress page for example?

Many thanks.

**Comment by andreruffert** [comment]
Of course! But I would say it has definitively nothing todo with the plugin :smile:
You could simply listen to normal `change/input` events and react to it e.g:

```html
<input type="range" min="1" max="5" step="1">
```

``` js
var urls = [
    'url1',
    'url2',
    'url3',
    'url4',
    'urls5'
];

$(document).on('change', 'input[type="range"]', function(e) {
    window.location = urls[e.target.value - 1];
});
```

**Comment by rossweston** [comment]
Okay cheers thats good.  Forgive me for being a touch thick on this one, but if I was to embed this javascript into a wordpress page, how would I go about doing that please?

**Comment by andreruffert** [comment]
So I'm not really into wp. I guess it depends... but you should be able to write a JS file and simply include it. Maybe [this](http://code.tutsplus.com/articles/how-to-include-javascript-and-css-in-your-wordpress-themes-and-plugins--wp-24321) will help you.

**Comment by rossweston** [comment]
Not to worry, its weak area for me integrating the two, putting WP aside, if you were to place into a normal html website what methodology would you use please?
