### ISSUE TITLE
Change example on http://andreruffert.github.io/rangeslider.js/ to use data-selector instead of input selector

### ISSUE THREAD

**Issue by neilbaylorrulez** [andreruffert/rangeslider.js#145]
This selector 
```
$('input[type="range"]').rangeslider();
```
fails in IE8 and 9

I think you should update your example usage to use a data-selector like:
```
$('[data-range]').rangeslider();
<input type="range" data-range>
```

So that your example usage works out of the box in IE8 and 9

Thanks!

**Comment by andreruffert** [comment]
Not sure what you mean...
It shouldn't be a problem to use a `$('input[type="range"]')` selector also in IE8 or IE9.

Tested this [CodePen](http://codepen.io/andreruffert/pen/yyEVrE) on IE8 Windows XP without any issues.

![bildschirmfoto 2015-04-21 um 22 44 24](https://cloud.githubusercontent.com/assets/464300/7262289/9aa2904a-e878-11e4-9c33-9d439817707c.png)

**Comment by neilbaylorrulez** [comment]
Ahh, you're right.

The issue comes up when you programatically add the input (with innerHTML or appendChlid)
When doing it this way, the IE parser strips the type="range" which will make the subsequent selector fail.

So it might still be good advice to use a data attribute (or a class) as the selector in your example usage - it would have saved me 5 minutes atleast :P

**Comment by andreruffert** [comment]
✅
