### ISSUE TITLE
Using rangeslider.js in RequireJS

### ISSUE THREAD

**Issue by ChuyUX** [andreruffert/rangeslider.js#155]
Hello,
I'm trying to call this script in RequireJS. Knowing that this plugins it's AMD enable, the definition that I'm using is this.

define(function (require) {
    var $ = require('jquery'),
        rangeslider = require('rangeslider');
    $('input[type="range"]').rangeslider({
    	polyfill: false
	});
});

But sometimes, this doesn't work, and gets me an error: TypeError: $(...).rangeslider is not a function
Hope you can help me out with this issue
Thanks

**Comment by andreruffert** [comment]
I would recommend  to take a look at the [RequireJS docs](http://requirejs.org/docs/jquery.html) again :)

_First of all you need a config to define the path to your files e.g._
```
require.config({
    paths: {
        'jquery': 'path/to/jquery',
        'rangeslider': 'path/to/rangeslider'
        ...
    }
});
```

_Now you can define your modules e.g_
```
define([
    'jquery',
    'rangeslider'
], function ($, rangeslider) {

  $('input[type="range"]').rangeslider({
    polyfill: false
  });

});
```

**Comment by ChuyUX** [comment]
Well, I forgot to mentioned and share that. I actually have this require.config with the each path defined as you put it previously. But, as I told you, this sometimes works and sometimes doesn't. I actually have another AMD ready plugins, like Slick, and it always works. So I know that someting I'm doing right.
I don't know if there is an error in the way you built the script to be AMD

**Comment by andreruffert** [comment]
K sorry no idea then. But the code how you load the modules doesn't look right to me. I personally use this plugin in an  AMD environment and it works perfectly with the code posted above.
