### ISSUE TITLE
can't get it to work. please help :)

### ISSUE THREAD

**Issue by sl1ck** [andreruffert/rangeslider.js#160]
Hi there, 
I absolutely love the slider. However, i am trying to customize it a little, and I am having trouble with the following code. The issue is that the user cannot input anything in the little rectangle that shows up for input. When I move the slider around, the values within the input  rectangle do change, but when i try to input something myself.. it just doesnt let me. how could i correct that? any ideas?

      <div style= "text-align:center; font-size: 30px; font-weight: bold">
				<form oninput="amount.value=rangeInput.value">
					<input  type="range" id="rangeInput" name="rangeInput" value = "0" min="0" max="100000" >
					<br>
					
					<input style="display: inline-block" name="amount" for="rangeInput"></input><p style= "display: inline-block">.00$</p>
					<br>
					<a class="btn btn-default" href="{{ pathFor 'portfolioPage' }}">Invest</a>
				</form>
	</div>
![image](https://cloud.githubusercontent.com/assets/13454153/8843391/c032e094-30d5-11e5-8aa3-b98b1a6ca4c2.png)

**Comment by andreruffert** [comment]
@sl1ck I made a [CodePen](http://codepen.io/andreruffert/pen/vOVygB?editors=101) which should help you.
