### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by mirraj2** [andreruffert/rangeslider.js#162]
I'm properly importing the css, jquery, and javascript.  There are no javascript errors in the console. The slider bar just stays exactly the same as without the plugin. I'm on chrome

```html
<body>
<input type="range" min="10" max="1000" step="10" value="300">

<script>
$('input[type="range"]').rangeslider();
</script>
</body>
```

**Comment by andreruffert** [comment]
#151 should help you :v:

**Comment by mirraj2** [comment]
Hrmm. I see. Well, I suggest you change the default so that polyfill is false. When I go to this url http://andreruffert.github.io/rangeslider.js/, I see a very pretty slider bar. That is the reason I chose to use this library. I expect that when I run the code that it will produce the result shown in that demo.  At the very least please post a big warning that the image shown will not actually be how the slider is rendered without additional settings changes.
