### ISSUE TITLE
Not working in Chrome, Safari and Firefox

### ISSUE THREAD

**Issue by rkb09** [andreruffert/rangeslider.js#168]
Hi, it seems rangeslider.js doesn't work in Chrome, FF and Safari. I've not tested in IE. I checked browser console and there was no error message. Check this online [demo](http://jsbin.com/ratahewuga).

**Comment by rkb09** [comment]
Seems like I have to pass the option `polyfill: false` in order to use it on browsers with native `<input type="range">` support.

Thanks, nice plugin :)

**Comment by walleykool** [comment]
Very correct.
