### ISSUE TITLE
Slider moving from text field input ?

### ISSUE THREAD

**Issue by vldy** [andreruffert/rangeslider.js#169]
Hi,
Is there a way for moving the slider after typing some value in a text field input ?

**Comment by andreruffert** [comment]
@vldy how would you do this for example for a normal `<input type="text">`?
The solution is the same :)

There are plenty examples how you can do this e.g. and it really doesn't have something to do with the rangeslider.js itself.

* http://andreruffert.github.io/rangeslider.js/#js-example-change-value
* http://codepen.io/andreruffert/pen/vOVygB
