### ISSUE TITLE
Make a version with no dependencies

### ISSUE THREAD

**Issue by jenstornell** [andreruffert/rangeslider.js#175]
It depends on jQuery. Make a version with no dependencies at all. Would be sweet!

**Comment by andreruffert** [comment]
Yep indeed! I also thought about it already :)
We'll see when I find the time to work on that.

**Comment by pirm-in** [comment]
+1

**Comment by dvLden** [comment]
+1

**Comment by mrksbnch** [comment]
I might find some time on the weekend to remove the jQuery dependency. If I do, I'll create a pull request...

**Comment by andreruffert** [comment]
https://github.com/andreruffert/range-slider-element
