### ISSUE TITLE
Event propagation stopped for moves -> rangesliders do not work anymore

### ISSUE THREAD

**Issue by ti-dev** [andreruffert/rangeslider.js#178]
I am using rangeslider in the latest version 2.0.2 for my project and it works great all the time.

Now I want to have my web pages swipeable and I use [Slick](https://github.com/kenwheeler/slick) so that I can swipe from one page to another one.

So my setup is that I have some web pages which are swipeable and inside these pages I have some rangesliders (horizontally arranged).

Trying to change the value of the rangeslider by sliding, the web page will start to swipe instead to change the slider position / value. This is because of event propagation and prevents me from changing the slider position / value.

So I tried to stop the event propagation by doing this: 
```javascript
$('.rangeslider').on('touchmove.slick mousemove.slick', function(event) {
    event.stopPropagation();
});
```
With this source code snippet, I can try to slide the rangeslider and the web page does not start to swipe, which is good, but the position / value of the rangeslider won't change.

The issue is because of the event propagation which I stopped.
In ``Plugin.prototype.handleDown`` there are these two lines:
```javascript
this.$document.on(this.moveEvent, this.handleMove);
this.$document.on(this.endEvent, this.handleEnd);
```
In my case, I stop the swiping of the web pages with Slick, because I stop the event propagation of the surrounding swipeable web page, but unfortunately I also stop it for the rangesliders, so it will never fire ``this.handleMove``. And inside this function there are the "calculations" / setPositions which will change the value / position of the slider.

So how can I solve this issue? Any help would be really appreciated!

**Comment by andreruffert** [comment]
Check [this](http://codepen.io/andreruffert/full/yYbXJP/) out!

:v:

**Comment by ti-dev** [comment]
@andreruffert Really great, but how did you do this and prevent it while sliding the slider, that Slick does not swipe?

**Comment by andreruffert** [comment]
@ti-dev just [click](http://codepen.io/andreruffert/pen/yYbXJP?editors=001) in the bottom left corner to see the code :)

![screen shot 2015-10-06 at 17 21 13](https://cloud.githubusercontent.com/assets/464300/10313259/11680e08-6c4f-11e5-90ca-ea892f0c12a3.png)

**Comment by mooru** [comment]
Thanks for the example of codepen but how does one make slick slider draggable with rangeslider?
