### ISSUE TITLE
Soft limits

### ISSUE THREAD

**Issue by webbson** [andreruffert/rangeslider.js#179]
I would really like a feature to set soft limits to the slider. So for example if I have min and max set to 0 and 100 but soft-min 20 and soft-max 60 the slider only allows to be set between 20 and 60 but still have the scale of 0 to 100.

**Comment by andreruffert** [comment]
@webbson thanks for your feature request but I don't plan to implement this to keep the plugin as simple as possible. For the features I oriented towards the [spec](http://www.w3.org/TR/html-markup/input.range.html).

But it should be possible to create such a look and feel by wrapping the slider element with another `div`  which has some padding with the soft-min, soft-max values and some styles.

:v:
