### ISSUE TITLE
rangeslider.js not working [solved]

### ISSUE THREAD

**Issue by philipp092** [andreruffert/rangeslider.js#182]
I just spent several hours trying to get the rangeslider up and running. 

The Problem:
It just wouldn't render the way it does on the website https://andreruffert.github.io/rangeslider.js/
It would stay exactly like an ugly defalut html input type="range" slider. No errors, no warnings, no instructions in the docs. 

The solution:

$('input[type="range"]').rangeslider({
     polyfill: false
});

___

How the hell should I suppose to know, that I have to seach for something like "POLYFILL" ?! This shloud be stated somewhere clearly as a comment. A thread named "polyfill" doesn't look very much like a solution to a simple problem that is "the thing is not working". 
This thread is for those out there looking for a solution as I did.

**Comment by andreruffert** [comment]
Hi @philipp092!

> How the hell should I suppose to know, that I have to seach for something like "POLYFILL" ?! This shloud be stated somewhere clearly as a comment. A thread named "polyfill" doesn't look very much like a solution to a simple problem that is "the thing is not working". 
This thread is for those out there looking for a solution as I did.

There is a [Options](http://andreruffert.github.io/rangeslider.js/#options) section which explains every available option.
![screen shot 2015-10-29 at 12 06 39](https://cloud.githubusercontent.com/assets/464300/10816753/94d1ef46-7e35-11e5-8fe2-55a8ec633c0b.png)

[This](https://github.com/andreruffert/rangeslider.js/issues/177#issuecomment-145367478) comment should make it a bit more clear to u what polyfill exactly means.

Anyway if you have any suggestions how to improve the [docs](https://github.com/andreruffert/rangeslider.js/tree/gh-pages) feel free to open an issue or submit a pr.

:v:

**Comment by danyj** [comment]
:100:  @philipp092 

@andreruffert    here how to update bud 


instead of saying  on homepage http://prntscr.com/8zhmuu and git home  http://prntscr.com/8zhmhw

  Usage :

    $('input[type="range"]').rangeslider();

change to 


    $('input[type="range"]').rangeslider({ polyfill: false });


or simply set polyfill to false by default and let users that need it in older browsers turn it on.

**Comment by konrados** [comment]
andreruffert: Hi.

Right now a guy on the #jquery irc channel solved a problem with the script after an hour of trying to find the bug. He simply didn't assume it may "deactivate" itself on newer browsers.

So I agree that the first example should be with polyfill: false.

**Comment by rbuelund** [comment]
I can still not get this to work. Nothing happens when setting polyfill: false;

**Comment by andersbrandt** [comment]
Spent 30 minutes looking at my build-chain before running into "polyfill: false".
This option should be default, I was very close to looking at other repos instead.

**Comment by neoteknic** [comment]
+1 all browser should support range input, so polyfill should be on by default...
