### ISSUE TITLE
Active slider handle style does not work in Mozilla

### ISSUE THREAD

**Issue by MarxAblir** [andreruffert/rangeslider.js#184]
When slider handle is clicked it does not have the UI pressed look in Mozilla.

In addition, Can I ask where does the focus go in this plugin when tabbed?

Thanks a lot in advance :)

**Comment by andreruffert** [comment]
> When slider handle is clicked it does not have the UI pressed look in Mozilla.

Hi! Thank's for mention. I fixed this in abc500b.
Looks like Firefox ignores the `:active` state if `e.preventDefault()` is set.

> In addition, Can I ask where does the focus go in this plugin when tabbed?

The focus goes on the `<input type="range">` element.

**Comment by MarxAblir** [comment]
Thanks a lot andre
