### ISSUE TITLE
What about a two button range slider for upper and lower bound values i.e. for price ranges?

### ISSUE THREAD

**Issue by sgrauel** [andreruffert/rangeslider.js#187]
Hello,

My name is Shawn Grauel. Open-source / freelance developer out of New York using Meteor and semantic-ui mostly to build an e-commerce shop and checkout system for multiple clients. I browsed the example page for this range slider and some of the issues quickly but saw no feature for implementing a double ended price filtering mechanism that integrates easily with meteor i.e. mechanism for filtering products within upper and lower bounds. I'm curious if any of you are already working on such a project or think it worthy of me to contribute. Just want to get your perspective here and not waste other people's time. Is this a worthy and valued endeavour? Best way to contact me is through google's hangouts

email: shawn.m.grauel@gmail.com
linked-in: https://www.linkedin.com/in/shawn-grauel-a6a6911a
skype: mr.sublime

All the best fellow webnauts

**Comment by andreruffert** [comment]
Rangeslider.js has no support for multiple handles. Maybe u should check http://refreshless.com/nouislider/ for that.

**Comment by sgrauel** [comment]
Thank you for the reference Andre. Let's not rebuild the wheel

Good luck to you

On Tue, Nov 24, 2015 at 4:33 PM, André Ruffert <notifications@github.com>
wrote:

> Rangeslider.js has no support for multiple handles. Maybe u should check
> http://refreshless.com/nouislider/ for that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andreruffert/rangeslider.js/issues/187#issuecomment-159411552>
> .
>



-- 

Shawn M. Grauel

704 West End Ave. Apt. 5A

New York, NY 10025

917-822-6870

shawn.m.grauel@gmail.com
