### ISSUE TITLE
JSPM error

### ISSUE THREAD

**Issue by linnett** [andreruffert/rangeslider.js#190]
This doesn't seem to be working with JSPM. I installed via 'jspm install' and imported the plugin. However, it appears to be returning an empty object. Is there a way around this?

**Comment by andreruffert** [comment]
I never used JSPM but since it's a jQuery Plugin you should be able to use it in jQuery context after importing it.

e.g.
````js
import $ from 'jquery';

// Load the plugin (make it available in jQuery).
// `rangeslider` will be `undefined` but that's ok :) 
import rangeslider from 'rangeslider.js'; 

$('input[type="range"]').rangeslider({polyfill: false});
````

**Comment by linnett** [comment]
Hi @andreruffert - thanks for the speedy response. It is now working! 
I believe I was referencing the file incorrectly. Thanks so much for the help and apologies for wasting your time :).
