### ISSUE TITLE
onSlide with steps

### ISSUE THREAD

**Issue by JaycobA** [andreruffert/rangeslider.js#191]
Hi,

I like what you did here so far, was looking through many sliders and yours looks pretty solid. One problem I have, though, is that I want to output the selected value in a different format, so I'm using an onSlide-callback to recalculate the output.

I'm using the slider to select a pretty large value with large stepping, but the onSlide-callback gets called on each new position calculation, not on every step which would be totally sufficient.

I'd love to help with the solution, but I'd like to discuss what to do first. I see two possibilities:
(a) fire onSlide only when new step is hit (by keeping track of last triggered step)
(b) use new callback (onStep?) and fire it only when a new step is hit

Semantically I'd prefer (a), but as that would be a breaking change it is probably better to implement (b). 

What do you think? If you agree, I would start implementing it.

Cheers
  Jaycob

**Comment by andreruffert** [comment]
Heya @JaycobA!

If I got u right there is a really simple solution :) Just use the `input` event e.g. 

```js
$('input[type=range]').on('input', recalculateOutput);
```

**Comment by JaycobA** [comment]
Huh, good catch. Must have overlooked that line, it is exactly what I need. Thank you very much :)

**Comment by andreruffert** [comment]
:v:
