### ISSUE TITLE
User select IE < 10

### ISSUE THREAD

**Issue by julmot** [andreruffert/rangeslider.js#192]
Have a look at the plugins [homepage](https://andreruffert.github.io/rangeslider.js/) in IE9 or IE8. Let's take the example "Orientation support" as an example. Slide the range to the top edge or bottom edge. You can see that this will select surrounding elements.

![eg](https://cloud.githubusercontent.com/assets/8310677/11592046/910baf54-9a9c-11e5-9b26-3bc6481e9d96.png)
Now you'll probably say

![grumpy-cat-8141_preview_zps9177ab07](https://cloud.githubusercontent.com/assets/8310677/11592064/a4d944c4-9a9c-11e5-91c7-4c86cdcacb62.png)

well, it's true.
I for example use the rangeslider as a video player volume control. If I slide to the edges the video gets selected. This is a very bad UX.
Using `user-select:none;` will not work because it's only supported in IE >= 10.

**Comment by andreruffert** [comment]
Kk I see it was introduced with another fix for firefox  and the `:active` state abc500b1494ffebd77d9463cd3a71844f08a52b5. I'll look into it.

**Comment by julmot** [comment]
Is there anything new?

**Comment by andreruffert** [comment]
Nopes didn't had time so far but feel free to contribute :)

**Comment by julmot** [comment]
Don't you think it would make more sense if the person wo created this bug solves it? I think if I would fix this issue I probably would create unwanted side effects because I'm not familar with the system requirements nor with the history of changes (like what you described).

**Comment by moloko** [comment]
FYI same thing happens in IE11 and Edge. 

Potential solution to only call event.preventDefault if browser == IE?

**Comment by julmot** [comment]
@moloko I don't use this project anymore, not solving this issue for months made me switching to another one.

**Comment by moloko** [comment]
well if [we](http://www.adaptlearning.org)  come up with a good fix/workaround we'll contribute it back

**Comment by RRorg** [comment]
Simple hack-ish fix for those unable to modify the library directly:

```
$('input[type="range"]').rangeslider({
  onInit: function() {
    $('.rangeslider__handle').on('mousedown touchstart mousemove touchmove', function(e) {
      e.preventDefault();
    })
  }
});
```
