### ISSUE TITLE
Firefox -- left and right arrow key don't work 

### ISSUE THREAD

**Issue by Daniel1989** [andreruffert/rangeslider.js#197]
Hi,

When I use tab key to focus on <input type="range">, I can use left arrow key and right arrow key to set different value in IE and chrome, but this not work in FF. Acutllay, in FF, value will change when use tab key again to lost focus, it just range handle can't show the move process when focus

**Comment by brunoais** [comment]
#195

**Comment by andreruffert** [comment]
Duplicate to #194.
