### ISSUE TITLE
2.0.5 is busted...

### ISSUE THREAD

**Issue by PowrSlave** [andreruffert/rangeslider.js#198]
I can't get it working in my project and also noticed the index.html file in the example folder isn't working either. Silently failing with no errors in console...

**Comment by andreruffert** [comment]
Hi @PowrSlave some more details would be great for example how do u try to initialize rangeslider.js (code) what browser are you using etc.

**Comment by PowrSlave** [comment]
OS X chrome, firefox, safari. example folder version doesn't work in any of these.

**Comment by PowrSlave** [comment]
![screen shot 2015-12-18 at 9 33 01 am](https://cloud.githubusercontent.com/assets/2702124/11901736/62836e0a-a56a-11e5-96ec-cbecd16ad1e6.png)

**Comment by brunoais** [comment]
Do not use the `file:` protocol

**Comment by k-lusine** [comment]
Hi. Set polifill to false, it helps!

**Comment by andreruffert** [comment]
Thanks @brunoais & @k-lusine :relaxed:
