### ISSUE TITLE
Window resize triggers onSlide callback

### ISSUE THREAD

**Issue by NotARobit** [andreruffert/rangeslider.js#199]
I'm not sure if this is intended functionality, but it was an unexpected behavior to me. I'm not sure why someone would want to trigger onSlide when the window is resized. It caused me problems because my onSlide callback assumes a slider has been changed and hides my application's results.

This happens because the window resize listener calls update() without any arguments, allowing the triggerSlide argument to default to true.

**Comment by andreruffert** [comment]
👍✨🎉
