### ISSUE TITLE
Cannot set value from localstorage

### ISSUE THREAD

**Issue by sadikyalcin** [andreruffert/rangeslider.js#205]
How can we populate the value of the slider from local storage? The "value" of the slider doesn't seem to be changing.

**Comment by andreruffert** [comment]
Hi @sadikyalcin! I guess it doesn't really have something to do with rangeslider.js itself but if u have some code how u trying to set the value from local storage I might help...

**Comment by sadikyalcin** [comment]
<input type="range" min="0" max="100" id="meetingProp" step="10" class="fader">

    var prop = document.querySelector('#meetingProp');
    
    this.loadData = function(el){
      if (typeof theKey !== 'undefined' && theKey !== null) {
        self.theData = localStorage.getItem(theKey);
        self.theData = JSON.parse(self.theData);
        return self.theData[el];
      }

      else {
        return false;
      }
    };
    ...
    var propValue = meetingsSpendSlide.loadData('meetingProp');
    prop.value = propValue;

I have tried both leaving the value out and with value + value as {{key}} too. Guessing you can't set "value" via js or jquery?

**Comment by andreruffert** [comment]
#### Some approaches:

__Set the `value` before the rangeslider.js initialization__
```js
...

$element
  .val(getValueFromLocalStorage())
  .rangeslider({...});
```

__Trigger a `change` event after setting the value__

```js
...

$element
  .val(getValueFromLocalStorage())
  .change();
```

__Call rangeslider.js `update` method__

```js
...

$element[0].value = getValueFromLocalStorage();
$element.rangeslider('update', true);
```

**Comment by sadikyalcin** [comment]
Thanks @andreruffert I fixed my problem. I just needed to initialise range slider after I set the value just like you mentioned. Maybe it might not have an affect but for future reference, I have left out the value in HTML and do a basic check in JS when populating from localstorage. If empty set value = X ...

**Comment by andreruffert** [comment]
🎉
