### ISSUE TITLE
Is range value banding possible?

### ISSUE THREAD

**Issue by NickMcBurney** [andreruffert/rangeslider.js#207]
Hi,

I was wondering if it is possible to spread the min/max values in a non-linear way?
For example lets say I have a slider with a min of 10 and a max of 100, I want the 10-50 range to be more spread out than the 50-100 range, e.g.:
instead of:
10-----50-----100
it would go:
10--------50--100

Thanks
Nick

**Comment by andreruffert** [comment]
Hello hi @NickMcBurney!

Out of the box rangeslider.js doesn't provide such functionality.
Did u came u with a possible solution already?
Maybe u could check http://refreshless.com/nouislider/examples/#section-non-linear
