### ISSUE TITLE
Slider with scroll ball at middle of the bar and on dragging need to move another ball

### ISSUE THREAD

**Issue by srinivas7** [andreruffert/rangeslider.js#210]
Hi, 
 I like this plugin very much. I have a requirement like slider has to be initialized with a ball at the middle of the slider bar. On dragging the ball, copy of the ball has to move to the left/right side. 

Can i achieve above requirement using this plugin???

**Comment by andreruffert** [comment]
Should be viable somehow. Did u made progress here yet?

**Comment by adewalegeorge** [comment]
@srinivas7 You can have a look at this idea. Your explanation is not very clear but have a look..
http://codepen.io/adewalegeorge/pen/RPORRv
