### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by vallurisundeep** [andreruffert/rangeslider.js#219]
Hi, 

I have 5 sliders in my page and want to append the selected range value to title attribute of "rangeslider__handle". I am able to append for first handle but I need for all 5 sliders.

**Comment by andreruffert** [comment]
If I got u right, something like this should work!

```
$('input[type=range]').rangeslider({
  polyfill: false,
  onSlide: function(pos, val) {
    this.$handle.attr('title', val);
  }
});
```

**Comment by vallurisundeep** [comment]
Thanks for your quick reply, but its working when I slide. I want it on load it self.You can refer the codepen URL for behaviour;

http://codepen.io/vallurisundeep/pen/QEWLxa

**Comment by andreruffert** [comment]
...
```js
onInit: function() {
  updateTitle(this.$handle[0], this.$element[0].value);
},
onSlide: function(pos, val) {
  updateTitle(this.$handle[0], val);
}
```
...
```js
function updateTitle(el, val) {
  el.setAttribute('title', val);
}
```

**Comment by andreruffert** [comment]
The `onInit` fn doesn't pass any arguments that's why u need to get the value by ur own.

**Comment by vallurisundeep** [comment]
Thank you so much, really appreciate.
