### ISSUE TITLE
Can I trigger a slideEnd event programmatically?

### ISSUE THREAD

**Issue by hustcer** [andreruffert/rangeslider.js#221]
Can I trigger a slideEnd event programmatically? Thanks.

**Comment by andreruffert** [comment]
@hustcer not quiet sure why u wanna do such thing 🙃 
My suggestion would be to simply use a change event on the input and e.g.

__1.__ trigger a change instead
__2.__ or call the fn directly which will be executed in the change callback 

```js

$('input[type=range]').on('change', doSomething);

// 1. trigger doSomething(); with a change event
$('input[type="range"]').change();

// 2. programmatically call doSomething();
doSomething();

function doSomething() {
  ...
}
```

**Comment by hustcer** [comment]
Great! Thanks very much.
