### ISSUE TITLE
jQuery 3.0 ios 9 Safari

### ISSUE THREAD

**Issue by swratten** [andreruffert/rangeslider.js#224]
This may be a known issue but I didn't get any results in search.

I haven't got any debug logs but using this library and jQuery 3.0.0 doesn't function correctly.

Steps to reproduce:

- Use jQuery 3.0.0 and latest rangeslider.
- Launch page on Safari in ios 9+
- Interact with slider
- Slider sticks at 0 (all the way to the left)

**Comment by andreruffert** [comment]
@swratten thanks :)

**Comment by JephMarketing** [comment]
I can also confirm the same behavior with iOS 9.3.2 on safari.

**Comment by andreruffert** [comment]
@JephMarketing should be fixed already in the latest version.

**Comment by JephMarketing** [comment]
hi @andreruffert sorry about that, forgot to update my cdn link... thanks for the great support!
