### ISSUE TITLE
incorrect work plugin with css -transform: scale() 

### ISSUE THREAD

**Issue by rustam87** [andreruffert/rangeslider.js#226]
when i use transform scale to wrapper for resize rangeslider, this incorrect working. Mouse and  rangeslider__handle different move

Example: https://jsfiddle.net/ghem9csy/

**Comment by andreruffert** [comment]
@rustam87 I tested your jsfiddle in Chrome + Firefox and it works for me.

**Comment by lzfxxx** [comment]
Encountered the same problem in Chrome, the mouse and slider do not match when dragging
