### ISSUE TITLE
It doesn't work,I want to know why.

### ISSUE THREAD

**Issue by HangZhouWan** [andreruffert/rangeslider.js#228]
I use the rangeslider.js like this:
`<script src="http://cdn.bootcss.com/jquery/3.1.0/jquery.min.js"></script>`

`<script  src="rangeslider.js"></script>`

 `<link  href="rangeslider.css" rel="stylesheet">`

the paths is right,but when I write in my jsfile 

`   $('input[type="range"]').rangeslider();`

 nothing happend , I'm sure selector is ok.
I don't know why.

**Comment by andreruffert** [comment]
https://github.com/andreruffert/rangeslider.js/issues/182 should solve your issue :)

**Comment by HangZhouWan** [comment]
thanks a lot .it's solved my problem
