### ISSUE TITLE
Does not work on iOS in combination with jQuery 3.1.0

### ISSUE THREAD

**Issue by av01d** [andreruffert/rangeslider.js#229]
If rangeslider.js is used in combination with jQuery 3.1.0, the slider is unresponsive in Safari for iOS.
Demo here: http://misc.avoid.org/rangeslider/
(Tried to make a jsFiddle, didn't work, hence this demo page)

**Comment by andreruffert** [comment]
@av01d using the latest version or at least [v2.2.0](https://github.com/andreruffert/rangeslider.js/releases/tag/v2.2.0) should fix that!

**Comment by av01d** [comment]
Thanks, it does indeed!
Can you please update the download link on this page http://rangeslider.js.org/ ?
It should point to the latest stable version, which seems to be 2.2.0 now...?
