### ISSUE TITLE
Rangeslider captures mousedown

### ISSUE THREAD

**Issue by luopio** [andreruffert/rangeslider.js#230]
I'm using rangeslider.js in a scenario where I need to fire an event when sliding begins. I figured I'd do this with 
```
$('input[type="range"]')
    .rangeslider({
      polyfill: false,
    })
    .on('mousedown touchstart', rangeSliderStart);
```

but rangeslider captures the mousedown and won't let it bubble up so `rangeSliderStart` is never called. If I change `polyfill` to `true` and use the native widget on Chrome it works as planned.

**Comment by andreruffert** [comment]
@luopio this should work in your case:

```js
// Adding the EventListener to the `document`.
// Event delegation helps us to call `rangeSliderStart` only
// if `e.currentTarget` is `.rangeslider`
$(document).on('mousedown touchstart', '.rangeslider', rangeSliderStart);
```

 

If you would really touch, mousedown the `$('input[type="range"]')` element it'll work but it's actually visually hidden :)

**Comment by luopio** [comment]
Ah I see. Thanks for the quick answer.
