### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by flamner** [andreruffert/rangeslider.js#232]
Hi, I include this plugin to may project, I make all right according to documentation, but nothing was changed :/ All files are included, plugin was initiated, input was added, but it still looks like as regular html range input, there are also no errors on console. I have no idea how to debug this issue and check what is wrong, any ideas?

**Comment by tiesont** [comment]
You're going to need to include something reproducible (like a JSFiddle or Bootply example) in order for anyone to help.

**Comment by JasonPhat** [comment]
I have the same issue:

codepen.io/anon/pen/yayxyg

**Comment by JasonPhat** [comment]
From this example http://codepen.io/andreruffert/pen/yyEVrE it seems to be to do with the polyfill value. The script will use html5 range input default if the browser supports it. The default polyfill value is true, so setting it to false will use the jquery generated input in all instances.
