### ISSUE TITLE
How do I make rangeslider__value-bubble individual to each slider?

### ISSUE THREAD

**Issue by orcfull** [andreruffert/rangeslider.js#235]
Hey,

I'm struggling to understand how to create specific value-bubbles for each slider. E.g rangeslider__value-bubble0 - rangeslider__value-bubble1 - rangeslider__value-bubble2 etc

Just like the handle and slider being 0-1-2-3 . is there an easy way to do it for value-bubble too?

I'm not a great coder, so apologise if this is a stupid question.

Thanks,

Alistair

**Comment by andreruffert** [comment]
@orcfull 

```js
var valueBubbleIndex = 0;

$('input[type="range"]').rangeslider({
  polyfill: false,
  onInit: function() {
    valueBubbleIndex++;
    appendValueBubble(valueBubbleIndex);
  }
});
```

Also check http://codepen.io/andreruffert/pen/nkbKv for an example how to create value bubbles
