### ISSUE TITLE
Android Browser issues with rangeslider 2.2.1 + jQuery 3.1.0

### ISSUE THREAD

**Issue by BrendanBerkley** [andreruffert/rangeslider.js#239]
http://codepen.io/BrendanBerkley/pen/jrJkpo

Doesn't work in Android Browser on Android 6.0; it jumps to zero whenever you try to slide. Changing the jQuery version to 2.1.3 (same as one of your [example pens](http://codepen.io/andreruffert/pen/qdWWZP)) makes it work.

Seems to work fine on Chrome. Not sure how much this error matters in terms of raw market share, but I thought I'd point it out anyways.

**Comment by ivanov-v** [comment]
I have the same problem
