### ISSUE TITLE
rangeslider__fill / 2 differents color for 2 differents slider

### ISSUE THREAD

**Issue by AlfredW0** [andreruffert/rangeslider.js#246]
Hello,
First, Thanks for you job @andreruffert, it's great to use.

I hope I don't ask for something easy, anyway I don't get trought it :+1: 
I have multiple rangeSlider in a web page and I like to display 2 differents colors for the low and high value of the result of each slide.
For exemple if 34%, dark blue.
if 87%, light blue.

I've tried to duplicate a rangeslider2 but the rangeslider appears twice.
Finally, I don't find the way to select the ID or class of my input to make something like :+1: 

` <input type="range" class="rangeslider2" value="35" step="1" min="1" max="100">`

`.rangeslider__fill .rangeslider2 {
	background: #EC0E11;
	position: absolute;
}`

Thanks a lot for help, if like !

Alfred

**Comment by ImBobby** [comment]
wrap each inputs with 2 different container class ([known as contextual style](http://www.english.hawaii.edu/zuern/394/Resources/change_links.html)). e.g:

```HTML
<div class="style-input-red">
  <input type="range">
</div>
<div class="style-input-blue">
  <input type="range">
</div>
```

```CSS
.style-input-red .rangeslider {
 background: red;
}

.style-input-blue .rangeslider {
 background: blue;
}
```
