### ISSUE TITLE
Slider Frozen

### ISSUE THREAD

**Issue by BTCBoss** [andreruffert/rangeslider.js#252]
Hi, 

For some reason, very randomly, my slider will stay frozen in place (cannot be dragged) sometimes when I load the page. Other times when I load the page, it is working fine. I cannot tell why or why it does not work. It always stays frozen all the way to the left, even though I default the value to 50. I console logged and the init function works as well ass the onSlideEnd function. The onSlideEnd function still works when the slider is frozen and cannot be dragged. 

Any help would be extremely appreciated. Thank you.

**Comment by Garfredo** [comment]
Hi BTCBoss,

I had same issue. If you use it with other jquery based scripts, let it run first or check out what the right sequence is.

**Comment by BTCBoss** [comment]
Thank you, Garfredo! I will give that a shot.

**Comment by Garfredo** [comment]
We use that slider in an environment with asynchronous loaded javascripts. Although the rangeslider script is starting only when all required scripts a present, you will see that issue sometimes - randomly. But only if you call the second page or use the site after minutes of inactivity and the files are ordered from the browsers cache.
Our fix: We integrated the css styles in our main css file that is loaded before js. 
We thinkt that it is important to load the rangeslider css before the script is running. 
For backing up any problems we implement an delay of the initialization:  setTimeout(function(){ $(slider) .rangeslider();}, 500);
