### ISSUE TITLE
Won't initialize

### ISSUE THREAD

**Issue by joshuao3** [andreruffert/rangeslider.js#253]
I have the most vanilla bare-bones file, and for some reason the slider won't initialize. (All I see is the normal browser slider. Inspecting the elements shows that no classes are attached to any elements) What am I doing wrong?

[!DOCTYPE HTML]
[html lang="en-US"]
  [head]
    [meta http-equiv="content-type" content="text/html;charset=utf-8"/]
    [script src="js/jquery-3.0.0.min.js"][/script]
    [script src="js/rangeslider.min.js">[/script]
    [link rel="stylesheet" href="css/rangeslider.css" /]
  [/head]
  [body]
[form]
[input type="range" min="10" max="1000" step="10" value="300" data-orientation="vertical" /]
[/form]
[script]
  $(document).ready(function () {
    $('input[type="range"]').rangeslider();
  });
[/script]
[/body]
</html>

Any help would be appreciated.

**Comment by Dnncha** [comment]
I'm having the same problem. I'm working with the example snippets and I'm seeing no errors but my range inputs are still default styled.

**Comment by jdefelice** [comment]
Try setting the polyfill to false, that worked for me when it wouldn't initialise.

`$('input[type="range"]').rangeslider({polyfill: false});`

**Comment by aeksco** [comment]
Just had the same issue - passing ```{ polyfill: false }``` did the trick.
