### ISSUE TITLE
2 draggable on a slide to define a range

### ISSUE THREAD

**Issue by Zmove** [andreruffert/rangeslider.js#254]
Hello,

I don't see any example where you can define a range with 2 draggable element (like [here](https://jqueryui.com/slider/#range))

Pretty funny for a plugin that is called "rangeslider".

Did I miss something or it's not doable at the moment ?

**Comment by shamrt** [comment]
👍

**Comment by thiagocoelho** [comment]
+1

Nice plugin by the way!

**Comment by andreruffert** [comment]
Currently there is no support for multiple handles but there is another plugin which supports multiple handles.

https://refreshless.com/nouislider/
