### ISSUE TITLE
Programmatically restrain sliding

### ISSUE THREAD

**Issue by kontur** [andreruffert/rangeslider.js#261]
I have a situation where several sliders are interdependent, so that one defines a minimum for the other which it can not go below. However, I do not want to restrain the actual min value of the slider and thus change the range, I'd just like to not move the slider handle beyond the programmatically restrained minimum.

**Comment by adewalegeorge** [comment]
You should look at my implementation on [codepen](https://codepen.io/adewalegeorge/pen/RPORRv)

**Comment by kontur** [comment]
Hey, the codepen doesn't show any sliders for me. Also, I have a custom implementation to achieve this on my problem - I would love it this could be a feature of the plugin.

**Comment by adewalegeorge** [comment]
Hi @kontur please check again, for some its due to issue on https request, I have corrected the link. [http://codepen.io/adewalegeorge/pen/RPORRv](http://codepen.io/adewalegeorge/pen/RPORRv)

**Comment by kontur** [comment]
Renders now, but I have no idea what the sliders are achieving or how they are interrelated. Thanks for the effort ;)

**Comment by adewalegeorge** [comment]
On the source there is a jsonData provided from which I use to set the available like init-val, min-val, max-val, response when a slide moves. Just like having presets for 
![image](https://cloud.githubusercontent.com/assets/3802751/25992559/cf370ff8-36fe-11e7-93f6-68e50e9cf427.png)

**Comment by anetk** [comment]
I have same situation. Did you end up making it work somehow @kontur ?

**Comment by kontur** [comment]
You can use the `onSlide` hook, store the value before applying, check if the slider remains within your desired limits, and if it does not, explicitly set the underlying `input` elements value to your limit. But this is somewhat clumsy ;)
