### ISSUE TITLE
Pips

### ISSUE THREAD

**Issue by jnorton** [andreruffert/rangeslider.js#265]
Hello, is there any way to show pips and labels with your awesome plugin? See image below for an example.

![screen shot 2017-06-09 at 14 18 09](https://user-images.githubusercontent.com/1861834/26977113-9a963234-4d1e-11e7-976c-06f1b52a373f.png)

**Comment by breadadams** [comment]
From what I can see this isn't supported _out of the box_. However should be pretty simple to get that working.

Just set the `step` prop on your `<input type="range" ... >` (4, in this case) and update its `value` on pip label click. Some style modifications would also be required 😁

**Comment by andreruffert** [comment]
Here is a codepen which does something similar.

https://codepen.io/andreruffert/pen/yyEVrE

**Comment by jnorton** [comment]
Many thanks for all of the code suggestions guys!
