### ISSUE TITLE
Input Range Problem

### ISSUE THREAD

**Issue by Avastia** [andreruffert/rangeslider.js#266]
Hello, I've tried to make this work with my store locator range slider. Currently, my slider only slides for mobile if I tap the spot I want it to move to; it does not move back and forth with my finger.

My store locator distance has 5,10,15,20,50,100 and All.

Rangeslider has input type in range slider format with input type range. Is it possible to put custom value as I have tried everything but unable to get it working.

**Comment by andreruffert** [comment]
@Avastia you should have a look at this [codepen](https://codepen.io/andreruffert/pen/dOJaZE) simply mapping the values could be a solution.

**Comment by Avastia** [comment]
Awesome, thank you @andreruffert I will give it a try.

**Comment by Avastia** [comment]
**Update:** The codepen tool definetly helped and we got it working! Thanks again!
