### ISSUE TITLE
Multiple sliders, update current slider handle not working

### ISSUE THREAD

**Issue by NathalieSpierings** [andreruffert/rangeslider.js#267]
I have used your sample:
https://codepen.io/andreruffert/pen/mJgvmq?editors=1010 

Now i have added another slider.
So now when there are two sliders, only the last handle get's updated.
I would expect that only the handle get's updated for the current slider.

**Comment by andreruffert** [comment]
@NathalieSpierings I have updated the example that it updates the handle like expected.

```js

// ...
.on('input', function(e) {

    // I'm selecting the `.rangeslider__handle` next to the element itself.
    // Before it was just referencing the global defined $handle[0] which was always the first handle.

    var $handle = $('.rangeslider__handle', e.target.nextSibling);
    updateHandle($handle[0], this.value);
  });
```
