### ISSUE TITLE
Slider width goes beyond the width size

### ISSUE THREAD

**Issue by anetk** [andreruffert/rangeslider.js#268]
If you move slider to the end it will go further then it's supposed to.
That happens only when I have set width.
Here is example: https://codepen.io/netk/pen/EXyJRY

Is this a bug? thoughts on how this could be fixed?

**Comment by andreruffert** [comment]
@anetk I don't see this happening in your example.
Setting the `width` to an wrapper element should solve this. 

e.g. 

```css
<style>
.wrapper {
  max-width: 300px;
}
</style>
```
```html
<div class="wrapper">
  <input type="range">
</div>
```
