### ISSUE TITLE
turn rangeslider element 180 degree

### ISSUE THREAD

**Issue by cojaco** [andreruffert/rangeslider.js#269]
Hello,

thanks for this cool plugin.

One question is it somehow possible to turn the slider by 180degree?

What I want to achive is a vertical slider where 0% is at the top and 100% at the bottom.

(I tried transform: rotate(180deg), but that dosenst work, because then the mouse y position is wrong )

**Comment by andreruffert** [comment]
rangeslider.js supports vertical orientation.

http://rangeslider.js.org/#usage

https://codepen.io/andreruffert/pen/meeOav

**Comment by cojaco** [comment]
yes, I know, but is there also a way to turn the slider by 180 degree?

I mean by default 100% is when the slider is up and 0% is when its down. But I wan't it the other way arround. 100% should be represented when the handle is down.
