### ISSUE TITLE
Not an issue but ...

### ISSUE THREAD

**Issue by cvelele** [andreruffert/rangeslider.js#270]
could not write in new pull request so,
is it possible that slider have two values changing ?
Like first one on http://rangeslider.js.org/ where value (500) is under and changing while you slide, to have another one above and changing months (January, February ,,) while you slide?

thx

**Comment by andreruffert** [comment]
@cvelele [here](https://codepen.io/collection/oeBwH/) are a bunch of examples which should help you to find a solution.
