### ISSUE TITLE
[Suggestion]Change height in vertical mode

### ISSUE THREAD

**Issue by michwii** [andreruffert/rangeslider.js#273]
Hi, 

I tried many options in order to increase the height of a slider in a vertical mode.

But could not find it.

```
<div class="u-cf">
        <h2><code>data-orientation="vertical"</code></h2>
        <div class="u-left" style="height: 800px">
            <input type="range" style="height: 800px" min="0" max="5" data-rangeslider data-orientation="vertical">
        </div>
```

It seems impossible. Am I right ?

Regards,

**Comment by andreruffert** [comment]
There is a new [release](https://github.com/andreruffert/rangeslider.js/releases/tag/v2.3.1) fixing this issue.

This should work with the latest version 2.3.1

```html
<div style="height: 400px">
  <input type="range" min="0" max="5" data-orientation="vertical">
</div>
```

**Comment by michwii** [comment]
Hi Andre,

Thank you for your quick response and your amazing library.

Unfortunately, it seems to don't work...

Here is a screenshot of the results I have : 
![Image of Error](https://ibb.co/jc3Dja)

**Comment by michwii** [comment]
I just correct it.

The modification shouldn't be on the scss file but on the css file.

:)

**Comment by andreruffert** [comment]
Seems to work for me https://codepen.io/andreruffert/pen/eRLEbz

**Comment by michwii** [comment]
For me too :)

Thank you Andre !
