### ISSUE TITLE
Added commas onto display for numbers

### ISSUE THREAD

**Issue by up637415** [andreruffert/rangeslider.js#278]
I have this code here which initiates the slider:

`jQuery("#slider").rangeSlider({
          bounds: {
               min: 300000,
               max: 625000
          },
          defaultValues: {
               min: 350000,
               max: 600000
          },
          step: 25000
     });`

I then bind the function to do a bunch of sorting in my HTML:
`jQuery("#slider").bind("valuesChanging", function(e, data) {
          pricingSort(data.values.min, data.values.max);
     });`

However, this is a price range, I include a dollar sign using a CSS before pseudo. 

I now want to include a comma between number values. I know I can use: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString to convert the number, but this will mess up my filtering as it is set to an integer and not a string. 

Is there a way to display a value and a label using this library?

**Comment by andreruffert** [comment]
@up637415 have a look at [this](https://codepen.io/andreruffert/pen/dOJaZE), it could be a possible approach.

**Comment by andreruffert** [comment]
Whoops just noticed you are using a different [plugin](http://ghusse.github.io/jQRangeSlider/) not sure how this one works under the hood...

**Comment by up637415** [comment]
Whoops my apologies!
