### ISSUE TITLE
Range slider not initialized properly when hidden

### ISSUE THREAD

**Issue by hoohoo23** [andreruffert/rangeslider.js#279]
I have a project and i used this range slider but some of my range sliders are hidden on start and when i try to use them thumb is unmovable any suggestions? i search in here but nothing worked

**Comment by andreruffert** [comment]
This should not be an issue. Check this [codepen](example) which demonstrates this case.

**Comment by andreruffert** [comment]
Whoops should work now!

👉 https://codepen.io/andreruffert/pen/gJfuq

**Comment by Eireen** [comment]
I have the same problem. It seems `getDimension()` does not work properly - `this.handleDimension` and `this.rangeDimension` are 0. FF 54, Ubuntu 14.04

**Comment by andreruffert** [comment]
@Eireen does the example [codepen](https://codepen.io/andreruffert/pen/gJfuq) work for you?

**Comment by Eireen** [comment]
@andreruffert yes, the example codepen works. I'll try to provide a reproducible example too a while later
