### ISSUE TITLE
Slider resize issue when changing screen mode

### ISSUE THREAD

**Issue by ayanez17** [andreruffert/rangeslider.js#281]
I have the following slider:

```
   <div class="slider" style="height: 80%">
        <input type="range" min="0" max="8" value="0" data-rangeslider data-orientation="vertical">
        <output></output>
        <div class="mbps">
          Mbps
        </div>
      </div>

```
As you can see the max value is 8.  When I'm in full screen mode, the slider button goes passes 8 ( not in value just position. This only happens when I'm in full screen mode. When I'm in  a smaller window size, or start from a smaller window size and then transition to full screen mode the issue does not persist.  Here is an image:
<img width="627" alt="screen shot 2017-08-17 at 11 13 05 am" src="https://user-images.githubusercontent.com/18299052/29419464-2ee87420-833d-11e7-9c64-1d17a4a9233c.png">

**Comment by andreruffert** [comment]
What exactly do you mean with full screen mode?

_Browser > view > Enter Full Screen_

![screen shot 2017-08-18 at 11 51 45](https://user-images.githubusercontent.com/464300/29454031-034e202e-840c-11e7-8ba4-28c4da0a54d7.png)

or are we talking about https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API

**Comment by ayanez17** [comment]
The former. When you go to full screen mode directly in the browser. The issue is there in both Chrome and Safari (10.1.2).

**Comment by andreruffert** [comment]
Can you reproduce it with this [example](https://s.codepen.io/andreruffert/debug/meeOav/dGkXWXgadzVA) as well?

**Comment by ayanez17** [comment]
The link doesn't work.

**Comment by andreruffert** [comment]
Damn! There you go https://codepen.io/andreruffert/full/meeOav/
