### ISSUE TITLE
Cannot get this to work at all!

### ISSUE THREAD

**Issue by rbuelund** [andreruffert/rangeslider.js#283]
I have inserted the js files:
`
<script src="/joomla/media/jui/js/jquery.min.js?953e40a5933b8ae643a6eb3739628812"></script>  
 <script src="/joomla/media/com_iamwith/js/rangeslider.min.js"></script>
`
and the javascript example with options:
`jQuery('input[type="range"]').rangeslider({
    polyfill: true,
    // Default CSS classes
    rangeClass: 'rangeslider',
    disabledClass: 'rangeslider--disabled',
    horizontalClass: 'rangeslider--horizontal',
    verticalClass: 'rangeslider--vertical',
    fillClass: 'rangeslider__fill',
    handleClass: 'rangeslider__handle',
    // Callback function
    onInit: function() {},
    // Callback function
    onSlide: function(position, value) {},
    // Callback function
    onSlideEnd: function(position, value) {}
});`

It does not do anything to my rangeslider at all
`   
<input type="range"
 min=0
max=100 
 step="1"
value=50
 data-orientation='horizontal'
  | >

`

**Comment by andreruffert** [comment]
https://github.com/andreruffert/rangeslider.js/issues/182

**Comment by rbuelund** [comment]
Setting polyfill to false did NOT solve the problem - it still renders as the normal ugly slider. Does not work for me in Chrome or Firefox

**Comment by andreruffert** [comment]
Any errors in the console? Maybe having a look at some working examples helps you figure out what's the issue in your case 👉 https://codepen.io/collection/oeBwH/

**Comment by rbuelund** [comment]
No errors in console. Only thing i did not add was this css:
.rangeslider__handle {
  width: 42px;
  height: 42px;
}
But still not working.
If I remove the rangeslider.min.js i see error in console, so the script is in use...

**Comment by andreruffert** [comment]
Sorry can't really help you then in this case...

All you need should be:

```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/rangeslider.js/2.3.1/rangeslider.min.css" />

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/rangeslider.js/2.3.1/rangeslider.min.js"></script>
<script>
$(function() {
  
  $('input[type=range]').rangeslider({
    polyfill: false
  });
  
});
</script>
```

**Comment by rbuelund** [comment]
Upps!! Very sorry.. a stupid jQuery error ! Had by mistake placed it outside my document ready ! Sorry for the inconvinience.

**Comment by rbuelund** [comment]
But now I have another question. Is it possible to set the fill color on-the-fly - through jQuery options ?

**Comment by andreruffert** [comment]
https://codepen.io/andreruffert/pen/XNGwjM

**Comment by rbuelund** [comment]
Hmm.. ok.. but I have 4 different sliders in the same form and I want to give them four different colors?

**Comment by andreruffert** [comment]
To be honest this has not really anything todo with this project it's more like general web development. Anyways I'll give you some cause for thought of one way you could do this...

What about just giving them different css classes?

E.g. 

```html
<input type="range" data-fill-class="color1">
<input type="range" data-fill-class="color2">

...
```

```css
.color1 {
  background-color: hotpink;
}

...
```

```js
$('input[type=range]').rangeslider({
    polyfill: false,
    onInit: function() {
      const fillClass = this.$element.data('fill-class');
      this.$fill.addClass(fillClass);
    }
  });
...
```
