### ISSUE TITLE
slider not reading position or value

### ISSUE THREAD

**Issue by Dirty-Nasty** [andreruffert/rangeslider.js#290]
Trying to get started with this plugin. Here's the code I have to initialize it.
```js
function dateSlider() {
    $('input[type="range"]').rangeslider({
        polyfill: false,
        min: 0,
        max: indexScaleLength,
        step: 1,
        onSlide: function(position, value) {
            console.log(position);
            console.log(value);
        }
    });
}
```
it only ever logs "0" to the console. What am I doing incorrectly?

**Comment by andreruffert** [comment]
@Dirty-Nasty if you are using this [plugin](http://rangeslider.js.org/) this should work.

rangeslider.js does not support __options__ like `min`, `max`, `step`. 
They should be attributes of the input element itself e.g: 
```html
<input type="range" min="0" max="10" step="1">
```

What exactly do you wanna achieve?
Also have a look at some this [codepen collection](https://codepen.io/collection/oeBwH/) for some examples.
