### ISSUE TITLE
rangeslider.js with a simple step ruler

### ISSUE THREAD

**Issue by bassemboulas** [andreruffert/rangeslider.js#295]
Hi,
I'm trying to add multiple rangeslider with a simple step ruler in one page, How can I initialize that to keep each one separate. Please help [https://codepen.io/andreruffert/pen/yyEVrE](url)
Thank you so much ;)

**Comment by bassemboulas** [comment]
@andreruffert 
Hi,
I'm trying to add multiple rangeslider with a simple step ruler in one page, How can I initialize that to keep each one separate. Please help https://codepen.io/andreruffert/pen/yyEVrE
Thank you so much ;)

**Comment by brijmohan** [comment]
Hi @bassemboulas ,

I want to the exact same thing. Have you been able to find the solution?

In my case, I just get the step ruler on the last rangeslider, not the previous ones.

Thanks

**Comment by andreruffert** [comment]
Creating a ruler element for each rangeslider instance should do the thing e.g.

```js
const $elements = $('input[type="range"]');

$elements.rangeslider({
  polyfill: false,
  onInit: function() {
    const $ruler = $('<div class="rangeslider__ruler" />');
    $ruler[0].innerHTML = getRulerRange(this.min, this.max, this.step);
    this.$range.prepend($ruler);}
});
```
