### ISSUE TITLE
I cant seem to find a way how to replace handle with my own svg element

### ISSUE THREAD

**Issue by viktorvesely** [andreruffert/rangeslider.js#308]
I tried to calculate it  based on position but it is always off when i change resolution. So is there a way how to change handle to svg icon ?

**Comment by viktorvesely** [comment]
Ok nvm sorry. Managed to do it by setting handle opacity to 0 and correctly calculate my new element position and reverse order icon is on the bottom handle is on the top to keep the functionality.

**Comment by AdamWiley46** [comment]
can you show me you version to do this please

**Comment by viktorvesely** [comment]
I dont know which version but here is my adaptation of the handle in the action
https://natural-bolt.glitch.me/

And here is the source code
https://glitch.com/edit/#!/natural-bolt - feel free to edit this by hitting "Remix project" button

**Comment by AdamWiley46** [comment]
thanks
