### ISSUE TITLE
Reset slider

### ISSUE THREAD

**Issue by piep14** [andreruffert/rangeslider.js#332]
Hello

It's possible de reset slider when click on button type reset ? 

Thanks

**Comment by andreruffert** [comment]
There is a `reset` event in the Web API ([reference](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reset_event)).

Combining the `reset` event with a programatic value change of the rangeslider.js API should be a possible solution.

[Programatic value change example](https://codepen.io/andreruffert/pen/vOVygB)
