### ISSUE TITLE
rangeslider is not working in IE9&10

### ISSUE THREAD

**Issue by zabishaik** [andreruffert/rangeslider.js#335]
Hi,
i tried the scenorio with attached link.

https://codepen.io/zabishaik6/pen/bPvZGW

in IE9 i can see inputbox insted of rangeslider and IE10  i can see compressed rangeslider

please help me out on that issue

Thanks in advance
zabi

**Comment by andreruffert** [comment]
Hi @zabishaik are the examples of https://rangeslider.js.org working like expected in IE9&10?

I noticed some things in your codepen which might cause the issues you describe:
- You are not initializing the rangeslider on DOM ready 
- You are using flexbox without vendor prefixes for IE10 https://caniuse.com/#search=flex
-

**Comment by zabishaik** [comment]
Hi @andreruffert thanks for your response,
flex issue in IE10 got resolved.
I have initialized range-slider in document.ready() then also i am facing issue in IE9.
please find attached snapshot.

thanks,
zabi
![sliderissue](https://user-images.githubusercontent.com/39787763/60532183-56a6e700-9d1a-11e9-86d7-857a4c625c66.PNG)

**Comment by zabishaik** [comment]
this issue got resolved by input type as 'text' and for class i added rangeslider() to class. its working fine in IE9. 
<input type="text" **class="range"**>
$('input[**class="range"**]').rangeslider({

@andreruffert  Thank u.

**Comment by tiesont** [comment]
Just FYI, if you're going to use a class selector, this makes more sense / is more concise:

```js
$('.range').rangeslider({ ... });
```
