### ISSUE TITLE
display:none dimensions

### ISSUE THREAD

**Issue by gabemart** [andreruffert/rangeslider.js#35]
To reproduce:

1) create a slider
2) note the value
3) set the slider element to `display: none`
4) resize the window
5) set the slider element to `display: block`

Expected behavior: the slider retains its previous value and is usable.

Observed behavior: the slider value changes to 50% of the slider range. The slider becomes unresponsive.

Workaround: `visibility: hidden; height: 0;` on the slider element works fine, but is not a direct replacement

**Comment by weebl2000** [comment]
Has this issue been fixed yet?
