### ISSUE TITLE
Disable single step and show as disabled

### ISSUE THREAD

**Issue by christophbee** [andreruffert/rangeslider.js#355]
Is there a way to disable a single step of the rangeslider? 

Example: By default there is a slider with 3 options for "Timing" (basically it's like duration for shipping): 
step 1 = 72h, step 2 = 24h and step 3 = 8h

Now I want to disable step 3 for certain cases but the rangeslider shall still show 3 steps where the last one is displayed as disabled like a disabled button and cannot be selected.

<img width="536" alt="Bildschirmfoto 2021-01-05 um 14 39 47" src="https://user-images.githubusercontent.com/22295289/103652763-de9b2c00-4f63-11eb-95d9-66bce4a02430.png">

**Comment by andreruffert** [comment]
> Is there a way to disable a single step of the rangeslider?

No.

---
I think a range slider is from a UX perspective not the ideal element to achieve this.
Instead I'd go with a `<input type="radio" />` group and some labels and use some basic CSS to achieve your UI design.

**Comment by christophbee** [comment]
Basically disabling the label is no problem but is there a common way how to show 3 steps but make 3rd stop not choosable? If not I have to check this via javascript on submit.

**Comment by christophbee** [comment]
If someone is looking for the same behaviour, this is to share my code how I solved it with custom javascript:

```
$r.rangeslider({
onSlideEnd: function (position, value) {
                var id = this.$element.attr('id');
                this.$handle.attr('title', value);

                if ($('#' + id).parent().hasClass('max-2-options')){
                    if (value == 3){
                        // if value is 3 slide back to value 2
                        value = value-1;
                        $('#' + id).val(value).change();
                    }
                }
```
