### ISSUE TITLE
Dynamically Updating Min / Max Values

### ISSUE THREAD

**Issue by sharpshark28** [andreruffert/rangeslider.js#80]
I can dynamically change the value of an input, but not the min or max attributes and have it adjust the slider? Thoughts on how this could be achieved?

> **Use Case:** I'm making a media player with a timeline that changes from video to video in a playlist. The total duration (the max) changes between videos.

**Comment by gingerbooth** [comment]
Has there been any progress on this? I really need to dynamically change the max value on a rangeslider. And I'm not even sure how I'd go about destroying and uncreating it.

**Comment by sharpshark28** [comment]
@gingerbooth I've had success with the following.

```
// Put your slider creation into a reusable function
function initSlider() {
  $('#mySlider').rangeslider({polyfill: false});
}
initSlider();
```

```
// Update the Maximum, Destroy, then Reinitialize the Slider
$('#mySlider').attr('max', 100).change();
$('#mySlider').rangeslider('destroy');
initSlider();
```

**Comment by gingerbooth** [comment]
Thank you very much for posting that, sharpshark28.

**Comment by ChiefORZ** [comment]
I've needed the same functionallity and added this:

	Plugin.prototype.updateOptions = function () {
		this.min = parseFloat(this.$element[0].getAttribute('min') || 0);
		this.max = parseFloat(this.$element[0].getAttribute('max') || 100);
		this.value = parseFloat(this.$element[0].value || this.min + (this.max - this.min) / 2);
		this.update();
	};

works like a charm. you just have to call it like:
$('#mySlider').rangeslider('updateOptions');

**Comment by andreruffert** [comment]
FYI: There is now a different approach for this see #139 for more details.

**Comment by nktailor** [comment]
Thanks for posting @sharpshark28

**Comment by barzoliub4o** [comment]
Thanks @sharpshark28  you are a genius. This work perfect.
